### ISSUE TITLE
Wrong dict lookup.

### ISSUE THREAD

**Issue by nettosama** [ehendrix23/aioharmony#1]
in harmonyclient.py, line: 745 and 752, it should be

```python
self._hub_config.devices
```

instead of

```python
self._hub_config.activities
```

**Comment by ehendrix23** [comment]
LOL, yeah. I already saw that and fixed it when some items were not working. :-)

Already got it fixed on my end. Working on some other parts as well hence not able to push an update. Will post here once done.

**Comment by ehendrix23** [comment]
FYI, this has been fixed now within the dev branch.
