### ISSUE TITLE
send_command does not work

### ISSUE THREAD

**Issue by goranpetrovikj** [ehendrix23/aioharmony#13]
I execute the following command, but without success... It says sent, but the command is not executed on the device.
```
aioharmony --harmony_ip <ip> send_command --device_id <id> --command=<command>
2019-08-18 00:25:49,163:WARNING:	slixmpp.stringprep	Using slower stringprep, consider compiling the faster cython/libidn one.
2019-08-18 00:25:50,326:INFO:	slixmpp.features.feature_bind.bind	JID set to: 1111/gatorade.
Connected to HUB 192.168.10.113 with firmware version 4.15.250
Command Sent
2019-08-18 00:25:51,842:INFO:	slixmpp.xmlstream.xmlstream	connection_lost: (None,)
```
However, https://github.com/misku/pyharmony works well - the command is actually executed:
```
harmony --harmony_ip <ip> send_command --device_id <id> --command=<command>
Command Sent
```

**Comment by ehendrix23** [comment]
Can you run the command with option: --loglevel DEBUG?
You are on aioharmony 0.2.0 correct?

Thx.

**Comment by DHJ1827** [comment]
When I execute a show_config, it takes 60 sec. to complete (current activity retrieval times out). But when I execute the same command with DEBUG turned on, it runs smoothly (current activity retrieved okay)
[aioharmony showconfig with debug.txt](https://github.com/ehendrix23/aioharmony/files/3990118/aioharmony.showconfig.with.debug.txt)
[aioharmony showconfig..txt](https://github.com/ehendrix23/aioharmony/files/3990119/aioharmony.showconfig.txt)

**Comment by ehendrix23** [comment]
Can you please make sure you are on the latest version of aioharmony (0.2.1). 
I tried here at home without debug. I have 2 HUBs, one using the XMPP protocol and another one that has web sockets enabled.
Both using show_config results in immediate response back.
