### ISSUE TITLE
Can you guys create a sample.py

### ISSUE THREAD

**Issue by fernaoguerra** [ehendrix23/aioharmony#19]
Hello there. I am new to github so I hope this is the right place to do this :)
I was wondering if you guys could add a sample.py page. 
I looked at the documentation, but still do not know how to use it. :(

Thanks in Advance.

**Comment by ehendrix23** [comment]
Do you mean how to use this in your own coding? Look at __main__.py as it is an example how to use the API.

**Comment by Morhoo** [comment]
Hi, i'm struggeling myself, it's not very intuitive for noobs, but for starter try this:

python3 -m pip install aioharmony
python3 -m aioharmony --harmony_ip x.x.x.x show_config

Now I need to study the code in order to figure out how to use send_command parameter...

**Comment by fernaoguerra** [comment]
Thanks @Morhoo. That edit really helped :)
No the problem I am facing is the fact that I am trying to use this like using python to run the commands. And I really think that's not the right way to do this.
Ex:

```
import os

def turn_on_the_tv():
    #this commnad turns the Tv on
    aioharmony --harmony_ip 192.168.0.10 send_command --command='PowerOn' --device_id=70487453
    #this commnad turns the cable on
    aioharmony --harmony_ip 192.168.0.10 send_command --command='PowerToggle' --device_id=70487369
```

Also, every time I run one of this codes it takes a loong to because it does not keep the the connection open... So it takes several seconds for each of the commands. 
It does not feel right. There should be a better way like using methods and I just can understand the lib.
Any luck from your side?

**Comment by fernaoguerra** [comment]
Thanks @Morhoo. That edit really helped :)
No the problem I am facing is the fact that I am trying to use this like using python to run the commands. And I really think that's not the right way to do this.
Ex:

import os

```
def turn_on_the_tv():
    #this commnad turns the Tv on
    aioharmony --harmony_ip 192.168.0.10 send_command --command='PowerOn' --device_id=700001
    #this commnad turns the cable on
    aioharmony --harmony_ip 192.168.0.10 send_command --command='PowerToggle' --device_id=700002
```

Also, every time I run one of this codes it takes a loong to because it does not keep the the connection open... So it takes several seconds for each of the commands.
It does not feel right. There should be a better way like using methods and I just can understand the lib.
Any luck from your side?

**Comment by Morhoo** [comment]
Well, for my intended use the fact it has to establish connection every time doesn't really matter. I don't need much performance. But I understand what you mean. I would expect some callable methods too: connect() / do_some_stuff() / close()... (and without doubt it's also what this module does internally, when you call __main__.py), so you don't have to pop shell from Python to use, well, Python... but to be honest, I'm not that good in it to say if this the case. I mean, you can always try to adopt some parts of original code like "from aioharmony import hamornyclient" for instance and play with it, but I'm only guessing. Hopefully someone else, more experienced, can give better explanation. I don't even know, how asyncio (which this is built upon) does exactly work. :( Sorry

**Comment by ehendrix23** [comment]
__main__.py is the example. It shows how you connect, get information, send commands, etc. using the API. 
In your own code you then import aioharmony.harmonyapi. Depending on what else you need you might also need to import some other small parts as you can see in __main__.py.

For connecting, see get_client in __main__.py. That then will return an object that is connected to your HUB.
Then see for example start_activity to start an activity on the hub. You use that client object to send the activity (client.start_activity you can see in that method).
For sending a command it is similar, see send_command method in __main__.py. 

Have a look at harmonyapi.py to see all methods available and information available. Anything starting with _ should not be used as that is considered private.

Hope this helps.
