### ISSUE TITLE
How do you pass the activity argument to start an activity?

### ISSUE THREAD

**Issue by wayner9** [ehendrix23/aioharmony#22]
I am trying to start an activity with a command like:

python3 /home/wayne/.local/bin/aioharmony --harmony_ip 192.168.1.203 start_activity "Watch TV"

But I get an error stating unrecognized arguments Watch TV.  I have also tried passing the number for the activity but that gives the same error.

How do I start an activity?

**Comment by ehendrix23** [comment]
If you do, for example:
```python3 /home/wayne/.local/bin/aioharmony start_activity -h```
then you get further help on it. Here it will show to use --activity <activity>. Thus for your  example it would be:
```python3 /home/wayne/.local/bin/aioharmony --harmony_ip 192.168.1.203 start_activity --activity "Watch TV"```

**Comment by wayner9** [comment]
Thanks you very much, so it looks like you can pass a string with the activity name or the activity ID integer, including -1 to do a power off.
