### ISSUE TITLE
Python 3.10 and 'loop' keyword is deprecated

### ISSUE THREAD

**Issue by warthog9** [ehendrix23/aioharmony#30]
Ran into https://github.com/home-assistant/core/issues/62510 and while trying to figure out what was going on I noticed that

https://github.com/swolix/aioharmony/commit/4c2c275e965d162a6ebb6a6e25e8eecc6e7f3c3a

has a fix for this already.  I've encouraged them to submit a PR, but wanted to add a tracking bug for this in case someone stumbles over this and to make the issue more known

**Comment by ehendrix23** [comment]
PR merged and 0.2.9 released with fix
