### ISSUE TITLE
Can this be used in the other way, to monitor for commands?

### ISSUE THREAD

**Issue by jwvanderbeck** [ehendrix23/aioharmony#33]
My end goal here is to find a smooth way of integrating Harmony into the larger Home Assistant ecosystem.  I know some people have done it with dummy Hue bridges but that's a brittle setup and very clunky.

This may have been already asked and answered so forgive me if it has been, but is it possible to use this API rather then sending commands, to be able to listen for commands? So that if I say press a button on the remote this could see that I did so?

**Comment by ehendrix23** [comment]
You can use the listen with wait option to see if it can see any of those but if I recall correctly that is not being send and hence unable to listen for things like that.
