### ISSUE TITLE
Harmony hub update 4.15.250 breaks aioharmony

### ISSUE THREAD

**Issue by amelchio** [ehendrix23/aioharmony#8]
Please see here for details: https://github.com/home-assistant/home-assistant/issues/21191

From the error message, I wonder if adding a Content-type is enough to fix it (but am not able to test at this time).

It would obviously be good if this could be resolved for the Home Assistant release that ships tomorrow since Harmony updates are rolling out right now.

**Comment by therve** [comment]
The message doesn't come from the server, but aiohttp. If you pass content_type=None to the response.json call, you get the actual error, which is {'code': '417'}. Unfortunately not much else.

**Comment by reneboer** [comment]
I found that the initial connection is now some TLSv1.2 session. Any idea on how to reverse engineer that?

If you have the remote_id of your Hub you can get it connected without the request_hub_info step.

**Comment by ehendrix23** [comment]
Version 0.1.8 resolves the issue.

Big thanks to @reneboer for providing the solution in https://github.com/home-assistant/home-assistant/issues/21191

Will be working on going to XMPP implementation now Logitech has provided the non-developer version for this.
